import fs from "fs";
import path from "path";
import { prisma } from "./db";
import { getSetting } from "./settings";

/**
 * Sync project metadata from DB to `{cwd}/.webmux/` so AI agents (Claude Code,
 * Codex, Cursor, …) can pick up project context in a vendor-neutral location.
 *
 * Files:
 *  - README.md   auto — index + agent pointer
 *  - project.md  auto — project overview
 *  - hosts.md    auto — deployment hosts
 *  - deploy.md   user — seeded if missing, never overwritten
 *  - test.md     user — seeded if missing, never overwritten
 *
 * Also cleans up the legacy `.claude/webmux-hosts.md` from when webmux wrote
 * into Claude Code's own namespace.
 */
export async function syncWebmuxDir(projectName: string): Promise<void> {
  const project = await prisma.project
    .findUnique({
      where: { name: projectName },
      include: { hosts: { orderBy: { env: "asc" } } },
    })
    .catch(() => null);

  if (!project?.cwd) return;

  // Migration: drop the old `.claude/webmux-hosts.md` if present. `.claude/`
  // is Claude Code's own dir — webmux should not squat there.
  const legacyPath = path.join(project.cwd, ".claude", "webmux-hosts.md");
  try { fs.unlinkSync(legacyPath); } catch { /* ignore */ }

  const dir = path.join(project.cwd, ".webmux");
  try { fs.mkdirSync(dir, { recursive: true }); }
  catch { return; /* project directory missing */ }

  // Local/remote classification
  const localHostSetting = await getSetting("localHost") || "";
  const localAliases = new Set(["localhost", "127.0.0.1", "local"]);
  if (localHostSetting) {
    localAliases.add(localHostSetting);
    const parts = localHostSetting.split("@");
    if (parts.length === 2) localAliases.add(parts[1]);
  }
  const isLocal = (target: string) => localAliases.has(target);

  const hasLocal = project.hosts.some((h) => isLocal(h.sshTarget));
  const hasRemote = project.hosts.some((h) => !isLocal(h.sshTarget));
  const status = project.hosts.length === 0
    ? "No hosts configured."
    : hasLocal && hasRemote
      ? "Mixed — some envs run on this machine, others deploy via SSH (see hosts table)."
      : hasLocal
        ? "Runs on this machine. Do NOT use SSH — run deploy commands directly in the project directory."
        : "Deploys via SSH to the hosts listed below.";

  // README.md — always written
  writeAuto(
    path.join(dir, "README.md"),
    [
      "# .webmux — Project Settings",
      "",
      "> Auto-maintained by [webmux](https://github.com/mrmu/webmux).",
      "> Files marked **auto** are regenerated — do not edit manually.",
      "> Files marked **user** are yours to edit; webmux will not overwrite them.",
      "",
      "## Files",
      "",
      "| File | Owner | Purpose |",
      "|------|-------|---------|",
      "| `README.md`  | auto | This file |",
      "| `project.md` | auto | Project overview |",
      "| `hosts.md`   | auto | Deployment hosts (managed in the webmux UI) |",
      "| `deploy.md`  | user | How to deploy this project |",
      "| `test.md`    | user | How to test / verify this project |",
      "",
      "## For AI agents",
      "",
      "These files contain authoritative project context. When deploying, testing, or",
      "reasoning about hosts, prefer the content here over ad-hoc notes elsewhere.",
      "",
    ].join("\n")
  );

  // project.md — always written
  writeAuto(
    path.join(dir, "project.md"),
    [
      `# ${project.displayName || project.name}`,
      "",
      "> Auto-generated by webmux. Do not edit manually.",
      "",
      `- **Name**: \`${project.name}\``,
      `- **Working directory**: \`${project.cwd}\``,
      `- **Deployment**: ${status}`,
      ...(project.description ? ["", `**Description**: ${project.description}`] : []),
      "",
    ].join("\n")
  );

  // hosts.md — always written (even with no hosts, so agents see the status)
  const hostLines: string[] = [
    "# Deployment Hosts",
    "",
    "> Auto-generated by webmux. Managed via the webmux UI — do not edit manually.",
    "",
    `**Status**: ${status}`,
    "",
  ];

  if (project.hosts.length > 0) {
    hostLines.push(
      "| Environment | Name | Target | Description |",
      "|------------|------|--------|-------------|",
      ...project.hosts.map(
        (h) =>
          `| ${h.env} | ${h.name} | ${isLocal(h.sshTarget) ? "localhost (本機)" : `\`ssh ${h.sshTarget}\``} | ${h.description} |`
      ),
      ""
    );

    const remoteHosts = project.hosts.filter((h) => !isLocal(h.sshTarget));
    if (remoteHosts.length > 0) {
      hostLines.push("## Deploy commands", "");
      for (const h of remoteHosts) {
        hostLines.push(
          `### ${h.name} (${h.env})`,
          "```bash",
          `ssh ${h.sshTarget}`,
          "```",
          ""
        );
      }
    }
  }
  writeAuto(path.join(dir, "hosts.md"), hostLines.join("\n"));

  // deploy.md / test.md — seed once, never overwrite
  seedUser(
    path.join(dir, "deploy.md"),
    [
      "# Deployment",
      "",
      "<!--",
      "  User-editable. webmux will not overwrite this file.",
      "  Document how to deploy this project to each environment.",
      "-->",
      "",
      "## Steps",
      "",
      "- [ ] ",
      "",
    ].join("\n")
  );

  seedUser(
    path.join(dir, "test.md"),
    [
      "# Test & Verification",
      "",
      "<!--",
      "  User-editable. webmux will not overwrite this file.",
      "  Document how to test and verify this project before/after deployment.",
      "-->",
      "",
      "## Before deploying",
      "",
      "- [ ] ",
      "",
      "## After deploying",
      "",
      "- [ ] ",
      "",
    ].join("\n")
  );
}

function writeAuto(filePath: string, content: string): void {
  try { fs.writeFileSync(filePath, content, "utf-8"); }
  catch { /* ignore */ }
}

function seedUser(filePath: string, content: string): void {
  if (fs.existsSync(filePath)) return;
  try { fs.writeFileSync(filePath, content, "utf-8"); }
  catch { /* ignore */ }
}

/** Single source of truth for what "has a webmux pointer" means in CLAUDE.md. */
export function hasWebmuxPointer(claudeMdContent: string): boolean {
  return /\.webmux\//.test(claudeMdContent);
}

/** The pointer block we append to CLAUDE.md / AGENTS.md / etc. */
export const WEBMUX_POINTER_BLOCK = [
  "",
  "## Project Settings (managed by webmux)",
  "",
  "Project-level configuration lives in [`.webmux/`](.webmux/). Consult these",
  "files when reasoning about hosts, deployment, or verification:",
  "",
  "- [`.webmux/project.md`](.webmux/project.md) — project overview",
  "- [`.webmux/hosts.md`](.webmux/hosts.md) — deployment hosts (auto)",
  "- [`.webmux/deploy.md`](.webmux/deploy.md) — deployment steps",
  "- [`.webmux/test.md`](.webmux/test.md) — test / verification procedures",
  "",
].join("\n");
