import fs from "fs";
import path from "path";
import { prisma } from "./db";
import { getSetting } from "./settings";

/**
 * Sync project metadata from DB to `{cwd}/.comux/` so AI agents (Claude Code,
 * Codex, Cursor, …) can pick up project context in a vendor-neutral location.
 *
 * Direction: DB → file. Auto files (README/project/hosts) are always
 * regenerated from DB. User files (deploy.md/test.md) are also regenerated
 * here, but the inverse pull (file → DB) lives in `importComuxDocsFromFile`
 * — call that first when the file may hold edits the DB doesn't know about
 * (e.g. an AI agent edited deploy.md directly, or the user opened the file
 * in their editor).
 *
 * Also cleans up the legacy `.claude/comux-hosts.md` from when comux wrote
 * into Claude Code's own namespace.
 */
export async function syncComuxDir(projectName: string): Promise<void> {
  const project = await prisma.project
    .findUnique({
      where: { name: projectName },
      include: { hosts: { orderBy: { env: "asc" } } },
    })
    .catch(() => null);

  if (!project?.cwd) return;

  // Migration: drop the old `.claude/comux-hosts.md` if present. `.claude/`
  // is Claude Code's own dir — comux should not squat there.
  const legacyPath = path.join(project.cwd, ".claude", "comux-hosts.md");
  try { fs.unlinkSync(legacyPath); } catch { /* ignore */ }

  const dir = path.join(project.cwd, ".comux");
  try { fs.mkdirSync(dir, { recursive: true }); }
  catch { return; /* project directory missing */ }

  // Local/remote classification
  const localHostSetting = await getSetting("localHost") || "";
  const localAliases = new Set(["localhost", "127.0.0.1", "local"]);
  if (localHostSetting) {
    localAliases.add(localHostSetting);
    const parts = localHostSetting.split("@");
    if (parts.length === 2) localAliases.add(parts[1]);
  }
  const isLocal = (target: string) => localAliases.has(target);

  const hasLocal = project.hosts.some((h) => isLocal(h.sshTarget));
  const hasRemote = project.hosts.some((h) => !isLocal(h.sshTarget));
  const status = project.hosts.length === 0
    ? "No hosts configured."
    : hasLocal && hasRemote
      ? "Mixed — some envs run on this machine, others deploy via SSH (see hosts table)."
      : hasLocal
        ? "Runs on this machine. Do NOT use SSH — run deploy commands directly in the project directory."
        : "Deploys via SSH to the hosts listed below.";

  // README.md — always written. Tracked in git (along with the rest of the
  // directory) so the convention travels with the repo; anyone cloning can
  // immediately understand the layout without installing comux.
  writeAuto(
    path.join(dir, "README.md"),
    [
      "# .comux — Project Settings",
      "",
      "> Auto-maintained by [comux](https://github.com/mrmu/comux).",
      "> Files marked **auto** are regenerated — do not edit manually.",
      "> Files marked **user** are yours to edit; comux will not overwrite them.",
      "",
      "## Files",
      "",
      "| File | Owner | Purpose |",
      "|------|-------|---------|",
      "| `README.md`  | auto | This file |",
      "| `project.md` | auto | Project overview |",
      "| `hosts.md`   | auto | Deployment hosts (managed in the comux UI) |",
      "| `deploy.md`  | user | How to deploy this project |",
      "| `test.md`    | user | How to test / verify this project |",
      "",
      "## For AI agents",
      "",
      "These files contain authoritative project context. When deploying, testing, or",
      "reasoning about hosts, prefer the content here over ad-hoc notes elsewhere.",
      "",
      "### Onboarding an existing project",
      "",
      "If the repository already documents deployment or testing elsewhere (a",
      "`## Deploy` section in `CLAUDE.md`, a `docs/deploy.md`, a shell script in",
      "`scripts/`, etc.), help the user consolidate it:",
      "",
      "1. Read the existing material and summarise it into concise, runnable steps.",
      "2. Ask the user to paste the summary into comux → Settings → Project Docs",
      "   (Deploy steps / Test checklist). comux stores it in the DB and",
      "   regenerates `deploy.md` / `test.md` here.",
      "3. Once the content is in comux, treat the files in this directory as the",
      "   canonical source going forward.",
      "",
      "Hosts (`hosts.md`) are managed in the comux UI under Settings → Hosts.",
      "",
    ].join("\n")
  );

  // project.md — always written. Intentionally portable: no absolute cwd
  // (the reader is already sitting in the project dir), so the file can be
  // committed without per-machine diff noise.
  writeAuto(
    path.join(dir, "project.md"),
    [
      `# ${project.displayName || project.name}`,
      "",
      "> Auto-generated by comux. Do not edit manually.",
      "",
      `- **Name**: \`${project.name}\``,
      `- **Deployment**: ${status}`,
      ...(project.description ? ["", `**Description**: ${project.description}`] : []),
      "",
    ].join("\n")
  );

  // hosts.md — always written (even with no hosts, so agents see the status)
  const hostLines: string[] = [
    "# Deployment Hosts",
    "",
    "> Auto-generated by comux. Managed via the comux UI — do not edit manually.",
    "",
    `**Status**: ${status}`,
    "",
  ];

  if (project.hosts.length > 0) {
    hostLines.push(
      "| Environment | Name | Target | Description |",
      "|------------|------|--------|-------------|",
      ...project.hosts.map(
        (h) =>
          `| ${h.env} | ${h.name} | ${isLocal(h.sshTarget) ? "localhost (本機)" : `\`ssh ${h.sshTarget}\``} | ${h.description} |`
      ),
      ""
    );

    const remoteHosts = project.hosts.filter((h) => !isLocal(h.sshTarget));
    if (remoteHosts.length > 0) {
      hostLines.push("## Deploy commands", "");
      for (const h of remoteHosts) {
        hostLines.push(
          `### ${h.name} (${h.env})`,
          "```bash",
          `ssh ${h.sshTarget}`,
          "```",
          ""
        );
      }
    }
  }
  writeAuto(path.join(dir, "hosts.md"), hostLines.join("\n"));

  // deploy.md / test.md — write DB to file. Caller is responsible for
  // calling importComuxDocsFromFile first if file edits should be pulled
  // into DB before this regen.
  const deployPath = path.join(dir, "deploy.md");
  const testPath = path.join(dir, "test.md");
  writeAuto(deployPath, project.deployDoc || DEPLOY_PLACEHOLDER);
  writeAuto(testPath, project.testDoc || TEST_PLACEHOLDER);
}

/**
 * Pull `.comux/deploy.md` and `.comux/test.md` content back into the DB
 * when the file has meaningful content the DB doesn't match. Use cases:
 *  - AI agent edited the file directly (Claude Code etc.)
 *  - User opened the file in an editor outside comux
 *  - Project existed before comux managed it and has hand-written docs
 *
 * Skips when:
 *  - File doesn't exist or is empty
 *  - File matches the placeholder (no real content)
 *  - File already matches DB (no-op)
 *
 * Returns which fields were imported so the caller can show feedback.
 */
export async function importComuxDocsFromFile(projectName: string): Promise<{
  deployImported: boolean;
  testImported: boolean;
}> {
  const project = await prisma.project
    .findUnique({ where: { name: projectName } })
    .catch(() => null);
  if (!project?.cwd) return { deployImported: false, testImported: false };

  const dir = path.join(project.cwd, ".comux");
  const deployFile = tryReadFile(path.join(dir, "deploy.md"));
  const testFile = tryReadFile(path.join(dir, "test.md"));

  // A file may look "non-empty" (has headings, HTML hints, empty `- [ ]`
  // checkboxes from a scaffolding template) without holding any real
  // user content. Strip those out and check whether anything substantive
  // remains — otherwise we'd import boilerplate over a real DB value.
  const stripScaffolding = (s: string) =>
    s
      .replace(/<!--[\s\S]*?-->/g, "")          // HTML comments
      .replace(/^\s*#+\s.*$/gm, "")             // markdown headings
      .replace(/^\s*-\s*\[\s*\]\s*$/gm, "")     // empty checkbox bullets
      .replace(/^_[^_\n]*_\s*$/gm, "")          // italic placeholder lines
      .trim();
  const hasRealContent = (s: string) => stripScaffolding(s).length > 0;

  const nextDeploy =
    hasRealContent(deployFile) && deployFile !== project.deployDoc
      ? deployFile
      : project.deployDoc;
  const nextTest =
    hasRealContent(testFile) && testFile !== project.testDoc
      ? testFile
      : project.testDoc;

  const deployImported = nextDeploy !== project.deployDoc;
  const testImported = nextTest !== project.testDoc;

  if (deployImported || testImported) {
    await prisma.project
      .update({
        where: { name: projectName },
        data: { deployDoc: nextDeploy, testDoc: nextTest },
      })
      .catch(() => {
        /* ignore — caller can retry */
      });
  }

  return { deployImported, testImported };
}

const DEPLOY_PLACEHOLDER =
  "# Deployment\n\n_Not yet documented — edit via comux → Settings → Deploy docs._\n";
const TEST_PLACEHOLDER =
  "# Test & Verification\n\n_Not yet documented — edit via comux → Settings → Test docs._\n";

function writeAuto(filePath: string, content: string): void {
  try {
    // Skip the write if the file already has the exact same content. Keeps
    // mtime stable across unrelated mutations so git / file watchers don't
    // flag `.comux/` as touched when nothing meaningful changed.
    const existing = fs.readFileSync(filePath, "utf-8");
    if (existing === content) return;
  } catch { /* no existing file — fall through to write */ }
  try { fs.writeFileSync(filePath, content, "utf-8"); }
  catch { /* ignore */ }
}

function tryReadFile(filePath: string): string {
  try { return fs.readFileSync(filePath, "utf-8"); }
  catch { return ""; }
}

/** Single source of truth for what "has a comux pointer" means in any agent file. */
export function hasComuxPointer(content: string): boolean {
  return /\.comux\//.test(content);
}

/** The pointer block we append to CLAUDE.md / AGENTS.md / etc. The "re-read"
 *  wording is deliberate — the files are DB-backed and can change via the
 *  comux UI between turns, so agents must not rely on earlier snapshots. */
export const COMUX_POINTER_BLOCK = [
  "",
  "## Project Settings (managed by comux)",
  "",
  "Project-level configuration lives in [`.comux/`](.comux/).",
  "**Before deploying, testing, or reasoning about hosts, re-read these",
  "files** — they may have been updated via the comux UI since you last",
  "loaded them. Do not rely on earlier snapshots.",
  "",
  "- [`.comux/project.md`](.comux/project.md) — project overview (auto)",
  "- [`.comux/hosts.md`](.comux/hosts.md) — deployment hosts (auto)",
  "- [`.comux/deploy.md`](.comux/deploy.md) — deployment steps",
  "- [`.comux/test.md`](.comux/test.md) — test checklist; walk every item and mark a deploy green only when all pass",
  "",
].join("\n");

/** Well-known agent-context filenames comux can manage pointers in.
 *  Each is plain markdown so the pointer block appends cleanly. */
export const AGENT_POINTER_TARGETS = [
  { filename: "CLAUDE.md", agent: "Claude Code" },
  { filename: "AGENTS.md", agent: "OpenAI Codex" },
] as const;

export function readPointerStatus(cwd: string, filename: string): {
  filename: string;
  exists: boolean;
  hasPointer: boolean;
} {
  const p = path.join(cwd, filename);
  try {
    const content = fs.readFileSync(p, "utf-8");
    return { filename, exists: true, hasPointer: hasComuxPointer(content) };
  } catch {
    return { filename, exists: false, hasPointer: false };
  }
}

/** Idempotently ensure the pointer block is present in `{cwd}/{filename}`.
 *  Creates the file (and any parent dirs) if missing. */
export function ensurePointer(cwd: string, filename: string): {
  ok: boolean;
  alreadyPresent: boolean;
  created: boolean;
} {
  const p = path.join(cwd, filename);
  let existing = "";
  let created = false;
  try {
    existing = fs.readFileSync(p, "utf-8");
  } catch {
    created = true;
  }
  if (hasComuxPointer(existing)) {
    return { ok: true, alreadyPresent: true, created: false };
  }
  fs.mkdirSync(path.dirname(p), { recursive: true });
  const separator = existing && !existing.endsWith("\n") ? "\n" : "";
  fs.writeFileSync(p, existing + separator + COMUX_POINTER_BLOCK, "utf-8");
  return { ok: true, alreadyPresent: false, created };
}
