import fs from "fs";
import path from "path";
import { prisma } from "./db";

/**
 * Sync project hosts from DB to .claude/webmux-hosts.md in the project directory.
 * Claude Code auto-reads .claude/ files as project context, so this ensures
 * it always has the correct deployment targets from webmux settings.
 */
export async function syncHostsFile(projectName: string): Promise<void> {
  const project = await prisma.project
    .findUnique({
      where: { name: projectName },
      include: { hosts: { orderBy: { env: "asc" } } },
    })
    .catch(() => null);

  if (!project?.cwd) return;

  const claudeDir = path.join(project.cwd, ".claude");
  const filePath = path.join(claudeDir, "webmux-hosts.md");

  if (project.hosts.length === 0) {
    // No hosts — remove the file if it exists
    try { fs.unlinkSync(filePath); } catch { /* ignore */ }
    return;
  }

  // Ensure .claude/ directory exists
  try { fs.mkdirSync(claudeDir, { recursive: true }); } catch { /* ignore */ }

  const lines = [
    "# Deployment Hosts (managed by webmux)",
    "",
    "> This file is auto-generated by webmux. Do not edit manually.",
    "> These hosts take priority over any hosts mentioned in CLAUDE.md.",
    "> If CLAUDE.md has different hosts, use these instead.",
    "",
    "| Environment | Name | SSH Target | Description |",
    "|------------|------|------------|-------------|",
    ...project.hosts.map(
      (h) => `| ${h.env} | ${h.name} | \`ssh ${h.sshTarget}\` | ${h.description} |`
    ),
    "",
    "## Deploy commands",
    "",
    ...project.hosts.map(
      (h) => `### ${h.name} (${h.env})\n\`\`\`bash\nssh ${h.sshTarget}\n\`\`\`\n`
    ),
  ];

  try {
    fs.writeFileSync(filePath, lines.join("\n"), "utf-8");
  } catch {
    // Project directory might not exist yet — ignore
  }
}
