import fs from "fs";
import path from "path";
import { prisma } from "./db";

/**
 * Sync project hosts from DB to .claude/webmux-hosts.md in the project directory.
 * Claude Code auto-reads .claude/ files as project context.
 */
export async function syncHostsFile(projectName: string): Promise<void> {
  const project = await prisma.project
    .findUnique({
      where: { name: projectName },
      include: { hosts: { orderBy: { env: "asc" } } },
    })
    .catch(() => null);

  if (!project?.cwd) return;

  const claudeDir = path.join(project.cwd, ".claude");
  const filePath = path.join(claudeDir, "webmux-hosts.md");

  if (project.hosts.length === 0) {
    try { fs.unlinkSync(filePath); } catch { /* ignore */ }
    return;
  }

  try { fs.mkdirSync(claudeDir, { recursive: true }); } catch { /* ignore */ }

  const isLocal = (target: string) =>
    target === "localhost" || target === "127.0.0.1" || target === "local";

  const lines = [
    "# Deployment Hosts (managed by webmux)",
    "",
    "> This file is auto-generated by webmux. Do not edit manually.",
    "> These hosts take priority over any hosts mentioned in CLAUDE.md.",
    "",
    "| Environment | Name | Target | Description |",
    "|------------|------|--------|-------------|",
    ...project.hosts.map(
      (h) =>
        `| ${h.env} | ${h.name} | ${isLocal(h.sshTarget) ? "localhost (本機)" : `\`ssh ${h.sshTarget}\``} | ${h.description} |`
    ),
    "",
  ];

  // Add local machine notice if any host is localhost
  if (project.hosts.some((h) => isLocal(h.sshTarget))) {
    lines.push(
      "## Important",
      "",
      "This project runs ON this machine. Do NOT use SSH to deploy.",
      "Run deployment commands directly in the project directory.",
      ""
    );
  }

  // Add deploy commands for remote hosts
  const remoteHosts = project.hosts.filter((h) => !isLocal(h.sshTarget));
  if (remoteHosts.length > 0) {
    lines.push("## Deploy commands", "");
    for (const h of remoteHosts) {
      lines.push(
        `### ${h.name} (${h.env})`,
        "```bash",
        `ssh ${h.sshTarget}`,
        "```",
        ""
      );
    }
  }

  try {
    fs.writeFileSync(filePath, lines.join("\n"), "utf-8");
  } catch {
    // Project directory might not exist yet
  }
}
